#!/bin/bash

# Exit on any error
set -e

# Source the longranger bash config
. /opt/longranger-2.1.2/sourceme.bash

# If not, Set timezone
if [ ! -e "/etc/timezone" ] && [ -z "${TZ}" ]; then
    export TZ="America/Chicago"
fi

# Allow running a bash session, otherwise pass everything to longranger
if [[ "$1" == *"bash" ]]; then
    /bin/env bash
else
    longranger "$@"
fi
